### ISSUE TITLE
ODE chart correlated to N

### ISSUE THREAD

**Issue by aquaxi** [alsnhll/SEIR_COVID19#8]
When I try to increase the N from 1000 to 100,000;  The plot changes dramatically, which it should not.  Did I miss anything ?  Thanks

**Comment by alsnhll** [comment]
The time course changes because by default, you always start with 1 infected individual. If you start with 1 out of 100,000 it takes a lot longer to reach a peak than if you start with 1 out of 1,000 infected. This is expected behavior. If you're talking about something else, please clarify. Thanks!

**Comment by zarak** [comment]
@aquaxi Just in case you're referring to the Python code in the notebook, `b` needs to be normalized by the population `N`.
